"""empty message

Revision ID: 2c5d973d831f
Revises: f2ebd45373f3
Create Date: 2022-03-16 13:39:08.224703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5d973d831f'
down_revision = 'f2ebd45373f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=True)
    op.alter_column('property', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'longitude',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('property', 'latitude',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
