"""empty message

Revision ID: 2d9f026ae31b
Revises: 5d318ece7046
Create Date: 2022-03-22 14:21:58.380956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9f026ae31b'
down_revision = '5d318ece7046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=True)
    op.alter_column('property', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'longitude',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('property', 'latitude',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
