"""empty message

Revision ID: 7334e9c29c46
Revises: 2c5d973d831f
Create Date: 2022-03-16 13:42:45.562018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7334e9c29c46'
down_revision = '2c5d973d831f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=True)
    op.alter_column('property', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'longitude',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('property', 'latitude',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
