"""empty message

Revision ID: f2ebd45373f3
Revises: a134f73a7425
Create Date: 2022-03-16 13:35:53.797338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ebd45373f3'
down_revision = 'a134f73a7425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.alter_column('property', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=True)
    op.alter_column('property', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=True)
    op.drop_constraint('property_ownerId_fkey', 'property', type_='foreignkey')
    op.create_foreign_key(None, 'property', 'user', ['owner_user_id'], ['id'])
    op.drop_column('property', 'ownerId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('ownerId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.create_foreign_key('property_ownerId_fkey', 'property', 'user', ['ownerId'], ['id'])
    op.alter_column('property', 'longitude',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('property', 'latitude',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('property', 'owner_user_id')
    # ### end Alembic commands ###
