"""empty message

Revision ID: f739b5841c87
Revises: 
Create Date: 2022-03-10 16:13:41.345664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f739b5841c87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('property',
    sa.Column('propertyCode', sa.Integer(), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('agency', sa.Boolean(), nullable=True),
    sa.Column('condition', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=1500), nullable=True),
    sa.Column('distance', sa.String(length=20), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('floor', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(precision=20), nullable=True),
    sa.Column('longitude', sa.Float(precision=20), nullable=True),
    sa.Column('municipality', sa.String(length=20), nullable=True),
    sa.Column('operation', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('propertyType', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('elevator', sa.Boolean(), nullable=True),
    sa.Column('bankOffer', sa.String(length=20), nullable=True),
    sa.Column('preservation', sa.String(length=20), nullable=True),
    sa.Column('contact_Name', sa.String(length=20), nullable=True),
    sa.Column('contact_Phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('propertyCode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    op.drop_table('user')
    # ### end Alembic commands ###
